### ISSUE TITLE
Same Origin Error2

### ISSUE THREAD

**Issue by harekujira** [wantora/weautopagerize#11]
YAHOO知恵袋(https://chiebukuro.yahoo.co.jp/)で検索したらAutoPagerizeやuAutoPagerizeで動作するのにweAutoPagerizeで動作しません。
url.host="ord.yahoo.co.jp"
location.host="chiebukuro.yahoo.co.jp"
次のページのURLのホストが違う場合も次のページを取得して欲しいです。

**Comment by wantora** [comment]
バージョン1.6.1で修正しました。
