### ISSUE TITLE
wedata down

### ISSUE THREAD

**Issue by hien4990** [wantora/weautopagerize#16]
it seem that i cannot access to wedata autopagerize, it seem down, uautopagerize is deleted from chrome, this extension and another like autopagerize advanced doesn't work, does anyone know what happen?

**Comment by SaltatorMortis** [comment]
like you said the database with the external stored templates is down right now.
will be probaby up in a few hours like always in the internet. And if not you need to build your own.

a simple workaround build your own autopager templates for the time beeing..
use the the addon 'uAutoPagerize XPath Tools' for simplifyed building if you have little knowlege about xpaths

**Comment by hien4990** [comment]
it's up again :)
btw do  you know the reason why the author of uautopagerize stopped support firefox? i see that the extension still in chrome but not update for a long time, so if i want to use uAutoPagerize XPath Tools i must use chrome?

**Comment by SaltatorMortis** [comment]
option one is use chrome for this tool
option two is to sideload(about:debugging) [this xpi](https://filebin.net/rnd953tqnv8lx95m/_634b1607-c163-400d-bb0c-7af378c1c32c_.xpi?t=v7ix9uj5) if you need it

as for the reason, no plan(maybe the addon page did a cleanup). the last update was ages ago but it still works for me and gives the good xpaths with strict anchestor/decendant limitations

PS if the issue [at least on my end it is] is solved close it

**Comment by wantora** [comment]
Fixed in version 1.7.0.
