### ISSUE TITLE
next page triggers twice

### ISSUE THREAD

**Issue by SaltatorMortis** [wantora/weautopagerize#18]
if you scroll your target website to the end/loadpoint prior its completly loaded, you will create two loading trees (seperate insert count)

here is the log:

> 19:26:57 test: {"url":"wuxiaworld\\.com/novel/","nextLink":"//a[@class=\"btn btn-link\"][img[@src=\"/images/arrow-right.png\"]]","pageElement":"(//div[@class=\"fr-view\"])[1]|(//div[@class=\"caption clearfix\"]/div/h4)[1]"}
> 19:26:57 start
> 19:26:58 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-222
> 19:26:58 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-222
> 19:26:59 insert: 2
> 19:26:59 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-223
> 19:26:59 insert: 3
> 19:26:59 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-224
> 19:27:00 insert: 2
> 19:27:01 insert: 4
> 19:30:29 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-223
> 19:30:29 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-225
> 19:30:33 insert: 3
> 19:30:33 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-224
> 19:30:33 insert: 5
> 19:30:33 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-226
> 19:30:33 insert: 4
> 19:30:34 insert: 6
> 19:57:41 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-225
> 19:57:41 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-227
> 19:57:41 insert: 5
> 19:57:41 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-226
> 19:57:42 insert: 6
> 19:57:42 loading: https://www.wuxiaworld.com/novel/sage-monarch/sm-chapter-227
> 19:57:43 insert: 7
> 19:57:44 insert: 7
> ... etc ...

**Comment by wantora** [comment]
Fixed in version 1.7.3. thank you!
