### ISSUE TITLE
Off button / exclusion rules are not working

### ISSUE THREAD

**Issue by neesema** [wantora/weautopagerize#19]
The Off option in the addon toolbar menu does not work and neither does the exclusion rules in the options. When the off button is pressed and the page reloaded, the extension reload and stays on as well ,and the exclusions rules do no prevent pagerizing.

**Comment by SaltatorMortis** [comment]
the off button disables until the page is reloaded
you are searching for:
on the autopagerbutton > 'right mouse button'=> "Disable the currend Tab/all Pages"
and for the blacklist are you using wildcards or regex?
to block all pages from github ie. github.com/wantora/weautopagerize
you could use
regex: `/github.com/`
wildcard: `*github.com*`

a literal `github.com` would block only the page github.com not its decendants

**Comment by neesema** [comment]
Thank you for those response. I was using the wrong formatting for the exclusions, my bad.
