### ISSUE TITLE
オプション画面の「SITEINFOを更新する」ボタンを押してもSITEINFOが更新されない

### ISSUE THREAD

**Issue by t-f-m** [wantora/weautopagerize#4]
諸々勘違いがあったので現在の問題にのみフォーカスして書き直します。

---

文春オンラインの分割記事をpagerizeするために wedata 上の SITEINFO を書き換えたのですが
旧) http://wedata.net/items/81222?rev=142657
新) http://wedata.net/items/81222?rev=145578
「SITEINFOを更新する」ボタンを押しても、更新されるのは表示上の更新日時だけで、どうやらSITEINFOが更新されていないようです。
文春オンラインの記事上で、weAutoPagerizeのアイコンを押して適用されているSITEINFOを確認したところ、旧バージョンのものが最初にヒットしていることが確認できました。

---
以下元の文
---
http://wedata.net/items/81222?rev=142657
http://wedata.net/items/81702?rev=145577
のように、同一のサイトに対するSITEINFOが競合している場合に、URL長の長い順にマッチングすることが期待されますが、実際には 81702 を解釈したあとは 400( http://wedata.net/items/400?rev=145247 )を解釈しに行っていました。
今回のケースでは、対象となるURLも同一だったのでSITEINFO自体もマージしてしまいましたが、今後も優先順位の問題で期待通りに動作しないケースが出てくることが予想されます。

**Comment by t-f-m** [comment]
すみません、こちらの勘違いでした……ソートは
https://github.com/wantora/weautopagerize/blob/9af369fe6cab3bc010161769d951e15d68dd1b15/src/lib/background/SiteinfoManager.js#L65
で実行されてますね。
SITEINFO側のマージ後も文春オンラインの記事で動作しないままなので、SITEINFOの更新系の問題のようです。

**Comment by wantora** [comment]
問題は解決したということでしょうか？

もしまだ問題があるなら、うまく動かなかったページのURLと、使用しているFirefoxとweAutopagerize
のバージョンを教えて頂けますか？

**Comment by t-f-m** [comment]
問題は解決していません。
使用しているのは、Firefox 59.0.1、weAutoPagerize 1.4.2 です。
問題があるページは http://bunshun.jp/articles/-/6676 をはじめとする文春オンラインの分割記事です。

**Comment by wantora** [comment]
恐らくFirefoxが http://wedata.net/databases/AutoPagerize/items_all.json をサーバに問い合わせずにキャッシュを返す事が原因です。
必ずサーバに問い合わせるように修正したバージョン1.4.3を addons.mozilla.org にアップロードしましたので、アドオンをアップデートして確認してみてください。

**Comment by t-f-m** [comment]
1.4.3 に更新して動作することを確認しました。ありがとうございます。
