### ISSUE TITLE
about:configによる特定サイトUA偽装時に継ぎ足されない

### ISSUE THREAD

**Issue by quroe** [wantora/weautopagerize#6]
about:configで`general.useragent.override.foo.bar`で文字列(UserAgent)を設定時に"https?:\/\/foo\.bar\/.+*"では指定したUserAgentが使われるのですが、次のページを継ぎ足す際にそのUserAgentを使用してくれないようです。
`general.useragent.override`で文字列(UserAgent)を設定時、こちらは閲覧サイト全てのUserAgentが設定した文字列に偽装されるのですがそちらでは継ぎ足されます。

・サイトサンプル
[http://morikinoko.com/archives/52096948.html](http://morikinoko.com/archives/52096948.html)

・about:config
`user_pref("general.useragent.override.morikinoko.com", "Mozilla/5.0 (Linux; Android 7.1.1; Nexus 6P Build/N4F26I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36");`

・User SITEINFO
[
  // スマホ向けLivedoorブログ汎用 個別記事
  {
    url: '^http://(?:blog\\.livedoor\\.jp|[a-z0-9]+\\.livedoor\\.biz||morikinoko\\.com)/',
    nextLink: '//p[@class="next"]/a',
    pageElement: 'id("article-contents")'
  },
]

Waterfox 56.2.3/Firefox 62.0+weAutopagerize 1.4.3で確認。
WE版uAutopagerizeでも同様の現象が起き、そちらでは以前にUser SITEINFOへ'userAgent': 'UAの文字列',追加でUA指定が出来るように対処していただけました。
その際の[やりとり](https://twitter.com/Griever2/status/941606412991340544)。

**Comment by wantora** [comment]
報告ありがとうございます。
バージョン 1.4.4 で修正しました。SITEINFO に "userAgent" を追加しなくても動きます。
